env:
  browser: true
  es2020: true
  node: true
extends:
  - standard
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier
ignorePatterns:
  - public/**/*
  - package-lock.json
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
settings:
  react:
    version: detect
rules:
  no-unused-vars: warn
  prettier/prettier: warn
