env:
  browser: true
  node: true
  es2020: true
extends:
  - standard
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - "plugin:@typescript-eslint/recommended"
ignorePatterns:
  - build/**/*
  - package-lock.json
plugins:
  - prettier
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
rules:
  no-unused-vars: warn
  prettier/prettier: warn
  sort-imports: [warn, { allowSeparatedGroups: true }]
  sort-keys: warn
  sort-vars: warn
  "@typescript-eslint/member-ordering":
    [warn, { default: { order: alphabetically } }]
  "@typescript-eslint/no-var-requires": off
