name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build the apps
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/electron/out/make/**/*.*/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
