name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32

      - name: Install Dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Build the binaries
        run: npm run build-bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/electron/out/make/**/*.*/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
